services:
  web:
    restart: always
    build: .
    ports:
      - 3000:3000
    environment:
      YT_API: ${YT_API}
      YT_SEARCH: ${YT_SEARCH}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
